on:
    workflow_call:
        inputs:
            run-name:
                required: false
                description: 'Name of the run'
                default: 'Running autodoc'
                type: string
            src:
                required: false
                description: 'Directory with code'
                default: 'src'
                type: string
            python-version:
                required: false
                description: 'Python version to download dependencies'
                default: '3.x'
                type: string
        secrets:
            GH_PAT:
                required: true
name: documentation
run-name: ${{ inputs.run-name }}
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
                submodules: 'recursive'
                token: ${{ secrets.GH_PAT }}
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: ${{ inputs.python-version }}
          - name: Display Python version
            run: python -c "import sys; print(sys.version)"
          - name: Install dependencies
            run: |
              pip install sphinx sphinx_rtd_theme myst_parser
          - name: Install project dependencies
            run: |
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Sphinx build
            run: |
              mkdir doc
              cd doc
              sphinx-quickstart -q -p ${{ github.event.repository.name }} -a AUVSL -v 1.0 --ext-githubpages --ext-viewcode --ext-coverage --extensions="sphinx.ext.napoleon","myst_parser","sphinx.ext.inheritance_diagram","sphinx.ext.todo","sphinx.ext.viewcode,sphinx.ext.autodoc,sphinx.ext.autosummary"
              sed -i '1i import sys\nimport os\nsys.path.append(os.path.abspath(".."))sys.path.append(os.path.abspath("..\/src/"))\n\nsys.path.append(os.path.abspath("..\/${{ inputs.src }}\/"))\nautodoc_mock_imports = ["rospy", "rclpy"]\nhtml_sidebars = {"**": [       "localtoc.html",        "globaltoc.html",        "relations.html",         "sourcelink.html",        "searchbox.html"   ]}\n' ./conf.py
              sed -i 's/alabaster/sphinx_rtd_theme/g' ./conf.py
              sphinx-apidoc -o source/ ../${{ inputs.src }}/ -a --implicit-namespaces -P
              sphinx-build . _build
          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v4
            if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_call') && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')}}
            with:
              publish_branch: gh-pages
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: doc/_build/
              force_orphan: true
